name: imagekit_ffi
description: A fast image conversion plugin with FFI.
version: 0.0.4
homepage: https://github.com/zhukeev/imagekit_ffi
issue_tracker: https://github.com/zhukeev/spoiler_widget/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

ffigen:
  output: lib/imagekit_ffi_bindings_generated.dart
  name: ImagekitFfiBindings
  description: Bindings for imagekit_ffi
  headers:
    entry-points:
      - src/imagekit_ffi.h

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
